type Dict = Record<string, unknown>;

const core: Dict = {
  app: {
    nom: "Sillage",
    eyebrow: "按体型选择尺码",
    tagline: "适合您运动方式的正确款式，适合您身体的正确尺码。",
    dataNote: "所有尺码表均来自厂商官方数据，经过收集与核实，绝不臆测。",
    langue: "语言",
  },
  steps: {
    progress: "进度",
    s1: "选择",
    s2: "使用情况",
    s3: "测量",
    s4: "结果",
    etape: "步骤",
  },
  buttons: {
    next: "继续",
    back: "返回",
    result: "查看结果",
    restart: "重新查询",
    pieces: "查看单品",
  },
  sel: {
    titre: "您的运动方式",
    sous: "请依次选择大类、项目和单品。我们只会询问该单品所需的测量数据。",
    famille: "大类",
    discipline: "项目",
    piece: "单品",
  },
  usage: {
    titre: "您的使用情况",
    sous: "几个简短的问题，帮助确定您想要的合身效果。",
    geneTitre: "之前使用的装备是否让您感到不适？",
    geneMulti: "请勾选所有感到的不适。每一项只会收紧该部位的容差。",
    jamais: "我从未穿过这类单品",
    oui: "是的，在某个特定部位",
    ou: "哪个部位？",
    choisirZone: "选择一个部位",
    tropSerre: "太紧",
    tropAmple: "太松",
  },
  mes: {
    titre: "您的测量数据",
    sous: "一根软尺就足够了。对这件单品至关重要的部位需要手工测量：这是自动估算最不可靠的地方。",
    determinant: "关键",
    facultatif: "可选",
    sansMesure: "没有这项测量数据仍可给出推荐，但该部位的精度会降低。",
    manque: "该单品缺少一项或多项关键测量数据。",
  },
  zones: {
    c: {
      label: "胸围",
      guide: "只穿内衣的状态下，将卷尺水平绕过胸部最丰满处测量。正常呼气，卷尺贴合但不勒紧。",
    },
    wa: {
      label: "腰围",
      guide: "在肋骨与髋骨之间腰部自然最细处测量。不要收腹，正常呼吸。",
    },
    hp: {
      label: "臀围",
      guide: "双脚并拢站立，测量髋部和臀部最丰满处。用镜子确认卷尺是否水平。",
    },
    th: {
      label: "大腿围",
      guide: "站立、腿部放松、体重均匀分布在双脚上，测量大腿最粗处。",
    },
    h: { label: "身高", guide: "脱鞋，背靠墙壁，双脚跟并拢，目视前方水平测量。" },
    wt: { label: "体重", guide: "早晨、未穿厚重衣物时测量。" },
    ij: { label: "内裆长", guide: "脱鞋、背靠墙壁，从裆部量到地面。" },
    bl: {
      label: "背长",
      guide: "从第7颈椎（T恤领口根部）量到髋骨位置的髂嵴。",
    },
    nk: { label: "颈围", guide: "在颈部根部水平绕量，卷尺不要勒紧。" },
    bc: { label: "上臂围", guide: "手臂自然垂放于身体两侧，测量上臂最粗处。" },
    sh: {
      label: "肩宽",
      guide: "肩部放松，从一侧肩峰经上背部量到另一侧肩峰。",
    },
    ws: {
      label: "臂展",
      guide: "背靠墙壁，双臂水平伸直，从一侧中指指尖量到另一侧中指指尖。",
    },
    al: {
      label: "臂长",
      guide: "手臂微屈，手放在髋部，从肩峰量到手腕褶皱处。",
    },
    tl: {
      label: "躯干长",
      guide: "从颈部根部经肩部量到裆部，再沿背部返回。",
    },
    ak: { label: "脚踝围", guide: "脚平放于地面，在踝骨正上方绕量，卷尺不要勒紧。" },
    dh: {
      label: "背部高度（髂嵴至肋骨）",
      guide: "站立状态下，沿躯干侧面从髂嵴量到浮肋。",
    },
    pv: { label: "骨盆围", guide: "腹部放松，在髂嵴高度水平绕量。" },
    il: {
      label: "髂嵴处腰围",
      guide: "将卷尺水平贴放在髂嵴正上方，不要压紧。",
    },
  },
  consent: {
    titre: "您的数据",
    intro:
      "默认情况下，本次会话是临时性的：您的测量数据仅在使用期间保留在内存中，不会被存储。所有选框默认均未勾选。",
    sessionL: "使用我的测量数据获取此次推荐",
    sessionD: "此为立即获得结果所必需。",
    profilL: "在会话结束后保留我的档案",
    profilD: "以便下次访问时找回您的测量数据。拒绝不会影响结果。",
    agregeL: "以汇总匿名的方式为改进服务做出贡献",
    agregeD: "绝不会关联回您的个人档案。",
    marchandL: "将推荐尺码发送给合作商家",
    marchandD: "仅发送尺码，绝不发送您的测量数据。",
    droits: "访问、更正、删除、数据可携带权及撤回同意，均可随时在界面中操作。",
  },
  res: {
    titre: "结果",
    refusTitre: "我们暂时无法给出答复",
    refusSuite:
      "您的测量数据已被纳入考量。一旦有品牌在该单品上达到我们要求的数据覆盖标准，推荐结果即可提供。",
    indepartageables: "两个品牌同样合适。相较于武断地二选一，我们更愿意如实告诉您。",
    coupeDeclaree: "官方标注的版型",
    sourceMarque: "品牌来源",
    sourceSecondaire: "二手来源",
    tracabilite: "本次诊断的可追溯信息",
    referentiel: "参考数据",
    parametres: "参数",
    horodatage: "时间戳",
  },
  // TRADUCTION MACHINE À RELIRE : quatre verdicts SILLAGE.
  verdict: { serre: "过紧", ajuste: "贴身", conforme: "合身", ample: "宽松" },
  confiance: {
    mot: "置信度",
    1: "非常低",
    2: "低",
    3: "中等",
    4: "高",
    5: "非常高",
  },
  repere: {
    mot: "基础知识",
    grille: "为什么一个品牌的整个系列只发布一张尺码表",
    mesurer: "正确测量：五条决定结果的规则",
    nonDit: "尺码表没有告诉你的事，以及我们为何要写出来",
  },
  steps2: { profile: "您的档案", measures: "您的测量数据", results: "您的尺码" },
  gender: { title: "使用的尺码表", m: "男款尺码表", f: "女款尺码表" },
  disc: {
    title: "项目",
    surf: "冲浪",
    eaulibre: "铁人三项／公开水域",
    plongee: "潜水／自由潜",
    ski: "滑雪与单板滑雪",
    harnais: "帆板／风筝冲浪安全带",
    soon: "即将推出",
    shoesRun: "跑步鞋",
    shoesSki: "滑雪靴",
  },
  buttons2: {
    toMeasures: "继续填写测量数据",
    compute: "计算我的尺码",
    edit: "修改我的测量数据",
    how: "如何测量",
    hide: "隐藏说明",
    more: "了解更多",
    optional: "可选",
  },
  issue: {
    title: "您最常在哪个部位感到不合身？",
    none: "没有特别的问题",
    thighs: "大腿与臀部",
    chest: "肩部与胸部",
    length: "长度（躯干、腿部）",
  },
  anchor: {
    title: "如果您已经拥有一件合身的湿衣，穿着感受如何？",
    none: "我没有／跳过此题",
    fit: "非常合身",
    tight: "太紧",
    loose: "太松，会进水",
    why: "这项信息有助于完善您的测量档案。",
  },
  results: {
    title: "各品牌推荐结果",
    bottom: "裤子",
    top: "夹克",
    ratioHW: "臀围／腰围比",
    ratioTH: "大腿／臀围比",
    perZone: "各部位详情",
  },
  warn: {
    noHips: "该品牌未提供足够的臀部相关信息，因此这方面的建议不确定性较高。",
    frontier: "在该品牌中，您正处于两个尺码之间。如条件允许，建议试穿。",
    empty: "目前我们尚无该类别的核实数据。",
    dimMissing: "该品牌未公布此项数据",
    biased: "该品牌的臀部版型偏紧：如有疑问，我们为您选择了更保险的尺码。",
    splitSizes: "夹克与裤子尺码不同是正常结果，并非异常情况。",
  },
  feedback: {
    title: "合身吗？",
    fit: "非常合适",
    tight: "太紧",
    loose: "太大",
    thanks: "感谢您的反馈，这有助于我们改进针对各种体型的建议。",
  },
};

const pages: Dict = {
  parcours: {
    mot: "阅读路径",
    tous: "全部",
    decouvrir: "初识",
    comprendre: "理解",
    approfondir: "深入",
    expert: "专家",
    lecture: "阅读时长",
  },
  disc: {
    mot: "项目",
    toutes: "全部",
    transversal: "跨项目",
    surf: "冲浪",
    "eau-libre": "公开水域／铁人三项",
    kite: "风筝冲浪／翼板",
    ski: "滑雪／单板滑雪",
    harnais: "安全带",
    plongee: "潜水",
    lab: "SILLAGE 实验室",
  },
  biblio: {
    eyebrow: "资料库",
    titre: "购买前先理解：从初次购买到专业进阶",
    sous: "尺码与合身度决定的是舒适度、保暖性和活动自如度，而不仅仅是外观。每篇文章都标明了其阅读路径与信息来源。",
    compteur: "篇文章",
    compteurUn: "篇文章",
    vide: "该项目在此阅读路径下暂无已发布文章。计划中的主题列示于下方：相较于草率发布内容，我们更愿意提前告知即将推出的内容。",
    lire: "阅读文章",
    replier: "收起",
    sources: "信息来源",
    prochainement: "即将推出",
    prochainementTitre: "计划中但尚未发布的主题",
    vague1: "第一批",
    vague2: "第二批",
    calendrier: "日程",
    calendrierTitre: "六个月的内容排期，逐月安排",
    calendrierVideo: "长视频",
    temps: "节奏",
    tempsTitre: "预计制作时长",
    tempsArticle: "文章",
    tempsVideo: "长视频",
    tempsShort: "短视频",
    teaser: "从初次购买到材料知识的各类文章，请选择您的阅读路径。",
    metaTitre: "资料库 — 理解尺码与合身度 | Sillage",
    metaDesc:
      "从初次购买到专业进阶的知识文章：湿衣、滑雪、安全带。哪些是已确立的事实，哪些来自品牌，哪些仍属未知。",
  },
  reperes: {
    eyebrow: "基础知识",
    titre: "选择之前先理解尺码",
    sous: "品牌实际公布了什么、没有公布什么，以及这对您意味着什么。此处所有内容均来自有据可查的信息来源，绝非推测。",
    metaTitre: "尺码基础知识 — Sillage",
    metaDesc: "了解尺码表、版型术语以及正确的测量方法，选出最适合的湿衣或山地装备。",
  },
  nav: {
    trouver: "查找我的尺码",
    biblio: "资料库：从初次购买到专业进阶",
    reperes: "尺码表基础知识",
  },
  langueTexte:
    "界面与摘要已翻译。文章正文仍保留法语原文，因为我们更看重经过校对的文字，而非机器翻译。",
  contenu: {
    flushing: {
      titre: "尺码过大，湿衣反而让您感到寒冷：进水效应的陷阱",
      chapo: "湿衣并不能让您保持干燥，它的作用是限制热交换和水的流动。",
    },
    "epaules-rame": {
      titre: "尺码过紧，可能导致划水时肩部过度疲劳",
      chapo: "过小的湿衣会压迫胸部或限制肩部活动，使每个动作都更加费力。",
    },
    "deux-centimetres": {
      titre: "2厘米的误差会改变什么",
      chapo: "如果这几厘米的误差恰好使您处于两个尺码的临界点，其影响就会变得至关重要。",
    },
    "meme-m": {
      titre: "为什么不同品牌的同一个「M」码意义并不相同",
      chapo: "并不存在一个通用的M码标准，能保证在任何地方都代表相同的尺寸。",
    },
    cou: {
      titre: "颈部密封性：尺码表极少提及的部位",
      chapo: "颈部是功能上非常重要的部位，但其周长却很少出现在公开的尺码表中。",
    },
    "morphologie-a": {
      titre: "梨形体型：为何一些尺码表无法很好地描述某些体型比例",
      chapo: "臀部和大腿较为丰满、腰部较细的体型：即使标注尺码相同，两人所需的版型可能截然不同。",
    },
    "pantalon-ski": {
      titre: "滑雪裤：为何臀部与大腿可能成为限制因素",
      chapo: "仅凭腰围是不够的，骨盆、大腿与内裆长共同决定了活动自如度和穿脱难易度。",
    },
    layering: {
      titre: "雪地叠穿：如何在夹克中留出适当空间而不显臃肿",
      chapo: "夹克需要容纳您的叠穿层，同时不显得过于臃肿。",
    },
    "compression-triathlon": {
      titre: "铁人三项：有益的压缩与有害的压缩",
      chapo: "铁人三项湿衣的设计需要贴身，但不应对呼吸或动作造成明显限制。",
    },
    "harnais-longueur-dos": {
      titre: "风筝冲浪安全带：背长同样重要",
      chapo: "选择安全带不能只看周长。",
    },
    "epaisseur-ajustement": {
      titre: "厚款与薄款：氯丁橡胶厚度如何影响合身度",
      chapo: "在结构相近的情况下，厚度增加通常会改变穿着时的柔韧感受。",
    },
    zip: {
      titre: "背拉链、前拉链或无拉链：对合身度的影响",
      chapo: "穿脱系统会改变湿衣的结构，进而影响活动自如度、进水情况和穿脱的便利性。",
    },
    "cinq-erreurs-mesure": {
      titre: "正确测量：五个会让一切失准的错误",
      chapo: "误差的根源往往在于不稳定的测量流程，而非卷尺本身。",
    },
    "cout-des-retours": {
      titre: "尺码不合适的衣物常被退货：退货的真实成本",
      chapo: "尺码与合身度是网购服装退货的主要原因之一。",
    },
    "essayage-et-conseil": {
      titre: "线下试穿与线上建议：如何巧妙结合",
      chapo: "实体店与数字化建议并非相互对立。",
    },
    "zone-par-zone": {
      titre: "为什么SILLAGE按部位分别考量",
      chapo: "功能性服装往往无法仅凭单一尺码标注来说明。",
    },
    "statique-dynamique": {
      titre: "静态合身度与动态合身度",
      chapo: "静止状态下看起来合适的装备，在运动中的表现可能截然不同。",
    },
    "meme-taille-comportement": {
      titre: "为何两件同尺码的湿衣表现会不同",
      chapo: "标签上的字母只能说明产品版型的一小部分。",
    },
    "donnee-inconnue": {
      titre: "SILLAGE如何处理未知数据",
      chapo: "数据的缺失本身也是一种信息。",
    },
    "apres-sml": {
      titre: "超越S、M、L：以多维视角看待合身度",
      chapo: "传统尺码将多维度的身体压缩进单一分类当中。",
    },
    "une-grille-par-marque": {
      titre: "为什么一个品牌的整个系列只发布一张尺码表",
      chapo:
        "在我们涉及的几乎所有项目中，各品牌都是按性别发布一张主尺码表，而非按每款产品分别发布。",
    },
    "vocabulaire-des-coupes": {
      titre: "版型术语及其真正含义",
      chapo: "修身、常规、宽松、剪裁贴身、舒适版型、性能版型：这些都是可以实际参考的官方用语。",
    },
    "ce-que-la-grille-ne-dit-pas": {
      titre: "尺码表没有告诉你的事",
      chapo: "尺码表只给出身体测量数据的区间，既不涉及材质，也不涉及弹性或拼接结构。",
    },
    "bien-mesurer": {
      titre: "正确测量：五条决定结果的规则",
      chapo: "卷尺使用不当会使推荐尺码整整偏差一个码。关键部位需要手工测量。",
    },
    debuter: {
      titre: "新手指南：购买前需要了解的三个基准",
      chapo: "合适的尺码首先取决于用途，其次才取决于品牌。",
    },
  },
};

const catalogue: Record<string, { l: string; d?: string }> = {
  A: { l: "氯丁橡胶湿衣", d: "水上运动用湿衣及相关单品。" },
  B: { l: "滑雪与单板滑雪", d: "山地服装、内层与外层夹克。" },
  C: {
    l: "水上运动安全带",
    d: "腰式安全带、坐式安全带、秋千式安全带。",
  },
  "C.fermeture": {
    l: "该大类将在品牌数据能够以可核实的方式覆盖背部高度后开放。相较于依据不确定的数据给出推荐，我们选择暂不推荐。",
  },
  A1: { l: "冲浪及浪板类运动", d: "冲浪、长板、俯式冲浪板。" },
  A2: {
    l: "公开水域与铁人三项",
    d: "游泳动作使肩部自由度成为最优先的限制因素。",
  },
  A3: {
    l: "风筝冲浪、翼板及混合用途",
    d: "佩戴安全带会对腰部和臀部产生额外的限制。",
  },
  A4: {
    l: "潜水",
    d: "水深带来的压缩使躯干合身度和腿长成为决定性因素。",
  },
  B0: { l: "滑雪与单板滑雪", d: "山地装备单品。" },
  "A1-integrale": { l: "全身湿衣", d: "长袖长腿。" },
  "A1-shorty": { l: "短袖湿衣", d: "短袖短腿。" },
  "A1-top": { l: "上衣", d: "仅氯丁橡胶上衣。" },
  "A2-integrale": { l: "游泳湿衣", d: "专为游泳设计的全身湿衣。" },
  "A3-integrale": { l: "全身湿衣", d: "穿于安全带内层。" },
  "A4-integrale": { l: "潜水湿衣", d: "湿式全身湿衣。" },
  B1: { l: "夹克", d: "外层夹克或保暖夹克。" },
  B2: { l: "长裤或背带裤", d: "标准尺码表最容易出现偏差的部位。" },
  B3: { l: "打底层或中间层", d: "功能性内层衣物。" },
  B4: {
    l: "连体服",
    d: "夹克与裤子一体化，对躯干长度有额外要求。",
  },
  "q.couches": { l: "您打算在里面穿中间层吗？" },
  "q.couches.fine": { l: "一层薄衣" },
  "q.couches.intermediaire": { l: "一层薄衣加一件抓绒" },
  "q.couches.epaisse": { l: "多层厚衣" },
  "q.couches.inconnu": { l: "还不确定" },
  "q.frequence": { l: "您参与该运动的频率如何？" },
  "q.frequence.occasionnel": { l: "每年几次" },
  "q.frequence.regulier": { l: "每月数次" },
  "q.frequence.intensif": { l: "每周或更频繁" },
  "q.temperature": { l: "您最常在什么水温下运动？" },
  "q.temperature.froide": { l: "低温，低于15°C" },
  "q.temperature.temperee": { l: "适中，15至20°C" },
  "q.temperature.chaude": { l: "温暖，高于20°C" },
  "q.preference": { l: "您更偏好哪种合身度？" },
  "q.preference.proche": { l: "贴身" },
  "q.preference.neutre": { l: "没有明显偏好" },
  "q.preference.aise": { l: "略微宽松" },
};

export default { core, pages, catalogue };
