/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as BibliothequeRouteImport } from './routes/bibliotheque'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as ReperesRouteImport } from './routes/reperes'
import { Route as EnForBusinessRouteImport } from './routes/en.for-business'
import { Route as EnStartRouteImport } from './routes/en.start'
import { Route as FrJeCommenceRouteImport } from './routes/fr.je-commence'
import { Route as FrPourLesEntreprisesRouteImport } from './routes/fr.pour-les-entreprises'
import { Route as NoForBedrifterRouteImport } from './routes/no.for-bedrifter'
import { Route as NoJegBegynnerRouteImport } from './routes/no.jeg-begynner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliothequeRoute = BibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ReperesRoute = ReperesRouteImport.update({
  id: '/reperes',
  path: '/reperes',
  getParentRoute: () => rootRouteImport,
} as any)
const EnForBusinessRoute = EnForBusinessRouteImport.update({
  id: '/en/for-business',
  path: '/en/for-business',
  getParentRoute: () => rootRouteImport,
} as any)
const EnStartRoute = EnStartRouteImport.update({
  id: '/en/start',
  path: '/en/start',
  getParentRoute: () => rootRouteImport,
} as any)
const FrJeCommenceRoute = FrJeCommenceRouteImport.update({
  id: '/fr/je-commence',
  path: '/fr/je-commence',
  getParentRoute: () => rootRouteImport,
} as any)
const FrPourLesEntreprisesRoute = FrPourLesEntreprisesRouteImport.update({
  id: '/fr/pour-les-entreprises',
  path: '/fr/pour-les-entreprises',
  getParentRoute: () => rootRouteImport,
} as any)
const NoForBedrifterRoute = NoForBedrifterRouteImport.update({
  id: '/no/for-bedrifter',
  path: '/no/for-bedrifter',
  getParentRoute: () => rootRouteImport,
} as any)
const NoJegBegynnerRoute = NoJegBegynnerRouteImport.update({
  id: '/no/jeg-begynner',
  path: '/no/jeg-begynner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/business': typeof BusinessRoute
  '/reperes': typeof ReperesRoute
  '/en/for-business': typeof EnForBusinessRoute
  '/en/start': typeof EnStartRoute
  '/fr/je-commence': typeof FrJeCommenceRoute
  '/fr/pour-les-entreprises': typeof FrPourLesEntreprisesRoute
  '/no/for-bedrifter': typeof NoForBedrifterRoute
  '/no/jeg-begynner': typeof NoJegBegynnerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/business': typeof BusinessRoute
  '/reperes': typeof ReperesRoute
  '/en/for-business': typeof EnForBusinessRoute
  '/en/start': typeof EnStartRoute
  '/fr/je-commence': typeof FrJeCommenceRoute
  '/fr/pour-les-entreprises': typeof FrPourLesEntreprisesRoute
  '/no/for-bedrifter': typeof NoForBedrifterRoute
  '/no/jeg-begynner': typeof NoJegBegynnerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/business': typeof BusinessRoute
  '/reperes': typeof ReperesRoute
  '/en/for-business': typeof EnForBusinessRoute
  '/en/start': typeof EnStartRoute
  '/fr/je-commence': typeof FrJeCommenceRoute
  '/fr/pour-les-entreprises': typeof FrPourLesEntreprisesRoute
  '/no/for-bedrifter': typeof NoForBedrifterRoute
  '/no/jeg-begynner': typeof NoJegBegynnerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/bibliotheque'
    | '/business'
    | '/reperes'
    | '/en/for-business'
    | '/en/start'
    | '/fr/je-commence'
    | '/fr/pour-les-entreprises'
    | '/no/for-bedrifter'
    | '/no/jeg-begynner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/bibliotheque'
    | '/business'
    | '/reperes'
    | '/en/for-business'
    | '/en/start'
    | '/fr/je-commence'
    | '/fr/pour-les-entreprises'
    | '/no/for-bedrifter'
    | '/no/jeg-begynner'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/bibliotheque'
    | '/business'
    | '/reperes'
    | '/en/for-business'
    | '/en/start'
    | '/fr/je-commence'
    | '/fr/pour-les-entreprises'
    | '/no/for-bedrifter'
    | '/no/jeg-begynner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BibliothequeRoute: typeof BibliothequeRoute
  BusinessRoute: typeof BusinessRoute
  ReperesRoute: typeof ReperesRoute
  EnForBusinessRoute: typeof EnForBusinessRoute
  EnStartRoute: typeof EnStartRoute
  FrJeCommenceRoute: typeof FrJeCommenceRoute
  FrPourLesEntreprisesRoute: typeof FrPourLesEntreprisesRoute
  NoForBedrifterRoute: typeof NoForBedrifterRoute
  NoJegBegynnerRoute: typeof NoJegBegynnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bibliotheque': {
      id: '/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof BibliothequeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reperes': {
      id: '/reperes'
      path: '/reperes'
      fullPath: '/reperes'
      preLoaderRoute: typeof ReperesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/for-business': {
      id: '/en/for-business'
      path: '/en/for-business'
      fullPath: '/en/for-business'
      preLoaderRoute: typeof EnForBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/start': {
      id: '/en/start'
      path: '/en/start'
      fullPath: '/en/start'
      preLoaderRoute: typeof EnStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/je-commence': {
      id: '/fr/je-commence'
      path: '/fr/je-commence'
      fullPath: '/fr/je-commence'
      preLoaderRoute: typeof FrJeCommenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/pour-les-entreprises': {
      id: '/fr/pour-les-entreprises'
      path: '/fr/pour-les-entreprises'
      fullPath: '/fr/pour-les-entreprises'
      preLoaderRoute: typeof FrPourLesEntreprisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no/for-bedrifter': {
      id: '/no/for-bedrifter'
      path: '/no/for-bedrifter'
      fullPath: '/no/for-bedrifter'
      preLoaderRoute: typeof NoForBedrifterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no/jeg-begynner': {
      id: '/no/jeg-begynner'
      path: '/no/jeg-begynner'
      fullPath: '/no/jeg-begynner'
      preLoaderRoute: typeof NoJegBegynnerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BibliothequeRoute: BibliothequeRoute,
  BusinessRoute: BusinessRoute,
  ReperesRoute: ReperesRoute,
  EnForBusinessRoute: EnForBusinessRoute,
  EnStartRoute: EnStartRoute,
  FrJeCommenceRoute: FrJeCommenceRoute,
  FrPourLesEntreprisesRoute: FrPourLesEntreprisesRoute,
  NoForBedrifterRoute: NoForBedrifterRoute,
  NoJegBegynnerRoute: NoJegBegynnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
